branch-defaults:
  master:
    environment: facebook-dev
global:
  application_name: facebook
  branch: null
  default_ec2_keyname: null
  default_platform: Ruby 3.0 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
packages:
  yum:
    postgresql-devel: []
